apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: petclinic
  template:
    spec:
      containers:
      - image: quay.io/seatechit/tthc:0.0.1-SNAPSHOT
  type: NodePort
